name: "Maven dependency tree submission"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '42 2 * * 1'

jobs:
  maven_dependency_tree_submission:
    runs-on: windows-latest
    steps:
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
